name: sbku_app
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  getwidget: ^7.0.0
  gradient_borders: ^1.0.0
  flutter_svg: ^2.1.6
  memory_cache: ^1.2.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.1
  # supabase_flutter: ^2.12.0
  sqflite: ^2.4.2
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  share_plus: ^12.0.2
  reorderable_grid_view: ^2.2.8
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.jpg"
  web:
    generate: true
    image_path: "assets/images/logo.jpg"
  windows:
    generate: true
    image_path: "assets/images/logo.jpg"

flutter_native_splash:
  color: "#FF5E00"
  android: true
  ios: true
  web: false
  android_12:
    color: "#FF5E00"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo.jpg
    - assets/images/campus.png
