services:
  - type: web
    name: sbkuapp
    env: docker
    rootDir: backend
    plan: free
    region: singapore
    disk:
      name: app-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://sbkuapp.onrender.com
      - key: APP_KEY
        value: base64:eOvGzttB2Sme3+YwJb7hse7ds1qCpwJ7HJ/KIdwHXKA=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: USE_FIRESTORE
        value: "false"
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_FILES
        value: /var/data/sessions
      - key: CACHE_STORE
        value: file
      - key: CACHE_FILE_PATH
        value: /var/data/cache
      - key: QUEUE_CONNECTION
        value: sync
      - key: AUTH_PROVIDER_DRIVER
        value: eloquent
      - key: FIREBASE_PROJECT_ID
        value: sbkuapp-vert25
      - key: FIREBASE_CREDENTIALS
        value: /etc/secrets/firebase-credentials.json
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-credentials.json
      - key: GOOGLE_CLOUD_USE_REST
        value: "true"
